### ISSUE TITLE
Question on path specification

### ISSUE THREAD

**Issue by atw374** [jabrell/eutl_scraper#12]
Hello! 
I have a small doubt about setting the path to my (local) data folder. I'm getting an error message 
FileNotFoundError: [Errno 2] No such file or directory: './data/tables/mainTransactionTypeCodes.csv'

I wondered whether I must manually set the path to my folder somewhere. Any hints on if (and eventually where) to adapt the py scripts would be much appreciated! Thanks

**Comment by jabrell** [comment]
Hi,

usually you don't have to set the path unless you want to use a different data folder. You need however to run the whole scratching procedure before and the table is created during the scratching.
