### ISSUE TITLE
Broken link to paper "Database for the European Union Transaction Log"

### ISSUE THREAD

**Issue by KSilkThread** [jabrell/eutl_scraper#4]
Dear Jan,

the topic is not directly affecting this repository, but is somehow linked. Im following your work quit a long time and would like to cite your paper "Database for the European Union Transaction Log" in my dissertation. Unfortunately the former link (https://www.euets.info/static//download/Description_EUTL_database.pdf) to the pdf version of your paper is broken. Would you be so kind to re-upload it somehow? Thanks a lot!

Best Regards
Karl

**Comment by jabrell** [comment]
Hi Karl,

the link is provided under the downloads page: [https://www.euets.info/download](https://www.euets.info/download). The link there goes to:
[https://euets-info-public.s3.eu-central-1.amazonaws.com/Description_EUTL_database.pdf](https://euets-info-public.s3.eu-central-1.amazonaws.com/Description_EUTL_database.pdf)

Best
Jan
